// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/proto/code_runner.proto

package coderunnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeExecutionService_ExecuteCode_FullMethodName         = "/com.levelupjourney.coderunner.CodeExecutionService/ExecuteCode"
	CodeExecutionService_GetExecutionStatus_FullMethodName  = "/com.levelupjourney.coderunner.CodeExecutionService/GetExecutionStatus"
	CodeExecutionService_HealthCheck_FullMethodName         = "/com.levelupjourney.coderunner.CodeExecutionService/HealthCheck"
	CodeExecutionService_StreamExecutionLogs_FullMethodName = "/com.levelupjourney.coderunner.CodeExecutionService/StreamExecutionLogs"
)

// CodeExecutionServiceClient is the client API for CodeExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for code execution - communicates with CodeRunner microservice (Go)
type CodeExecutionServiceClient interface {
	// Execute solution code and return approved test IDs
	ExecuteCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	// Get execution status for monitoring
	GetExecutionStatus(ctx context.Context, in *ExecutionStatusRequest, opts ...grpc.CallOption) (*ExecutionStatusResponse, error)
	// Health check for service monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Stream execution logs in real-time
	StreamExecutionLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type codeExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeExecutionServiceClient(cc grpc.ClientConnInterface) CodeExecutionServiceClient {
	return &codeExecutionServiceClient{cc}
}

func (c *codeExecutionServiceClient) ExecuteCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, CodeExecutionService_ExecuteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeExecutionServiceClient) GetExecutionStatus(ctx context.Context, in *ExecutionStatusRequest, opts ...grpc.CallOption) (*ExecutionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionStatusResponse)
	err := c.cc.Invoke(ctx, CodeExecutionService_GetExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeExecutionServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CodeExecutionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeExecutionServiceClient) StreamExecutionLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeExecutionService_ServiceDesc.Streams[0], CodeExecutionService_StreamExecutionLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeExecutionService_StreamExecutionLogsClient = grpc.ServerStreamingClient[LogEntry]

// CodeExecutionServiceServer is the server API for CodeExecutionService service.
// All implementations must embed UnimplementedCodeExecutionServiceServer
// for forward compatibility.
//
// Service for code execution - communicates with CodeRunner microservice (Go)
type CodeExecutionServiceServer interface {
	// Execute solution code and return approved test IDs
	ExecuteCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	// Get execution status for monitoring
	GetExecutionStatus(context.Context, *ExecutionStatusRequest) (*ExecutionStatusResponse, error)
	// Health check for service monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Stream execution logs in real-time
	StreamExecutionLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedCodeExecutionServiceServer()
}

// UnimplementedCodeExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeExecutionServiceServer struct{}

func (UnimplementedCodeExecutionServiceServer) ExecuteCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedCodeExecutionServiceServer) GetExecutionStatus(context.Context, *ExecutionStatusRequest) (*ExecutionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionStatus not implemented")
}
func (UnimplementedCodeExecutionServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCodeExecutionServiceServer) StreamExecutionLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamExecutionLogs not implemented")
}
func (UnimplementedCodeExecutionServiceServer) mustEmbedUnimplementedCodeExecutionServiceServer() {}
func (UnimplementedCodeExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeCodeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeExecutionServiceServer will
// result in compilation errors.
type UnsafeCodeExecutionServiceServer interface {
	mustEmbedUnimplementedCodeExecutionServiceServer()
}

func RegisterCodeExecutionServiceServer(s grpc.ServiceRegistrar, srv CodeExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedCodeExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeExecutionService_ServiceDesc, srv)
}

func _CodeExecutionService_ExecuteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeExecutionServiceServer).ExecuteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeExecutionService_ExecuteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeExecutionServiceServer).ExecuteCode(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeExecutionService_GetExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeExecutionServiceServer).GetExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeExecutionService_GetExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeExecutionServiceServer).GetExecutionStatus(ctx, req.(*ExecutionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeExecutionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeExecutionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeExecutionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeExecutionServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeExecutionService_StreamExecutionLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeExecutionServiceServer).StreamExecutionLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeExecutionService_StreamExecutionLogsServer = grpc.ServerStreamingServer[LogEntry]

// CodeExecutionService_ServiceDesc is the grpc.ServiceDesc for CodeExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.levelupjourney.coderunner.CodeExecutionService",
	HandlerType: (*CodeExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCode",
			Handler:    _CodeExecutionService_ExecuteCode_Handler,
		},
		{
			MethodName: "GetExecutionStatus",
			Handler:    _CodeExecutionService_GetExecutionStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CodeExecutionService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecutionLogs",
			Handler:       _CodeExecutionService_StreamExecutionLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/code_runner.proto",
}
